<a href="https://colab.research.google.com/github/MrGupa/MrGupa/blob/main/Titanic_Survival.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle

In [4]:
df = pd.read_csv("/content/titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
df = df[['Pclass','Sex','Age','Embarked','Survived']]
df.sample(5)

Pclass     Sex   Age Embarked  Survived
247       2  female  24.0        S         1
337       1  female  41.0        C         1
224       1    male  38.0        S         1
669       1  female   NaN        S         1
764       3    male  16.0        S         0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    891 non-null    int64  
 1   Sex       891 non-null    object 
 2   Age       714 non-null    float64
 3   Embarked  889 non-null    object 
 4   Survived  891 non-null    int64  
dtypes: float64(1), int64(2), object(2)
memory usage: 34.9+ KB


In [7]:
df.isnull().sum()

Pclass        0
Sex           0
Age         177
Embarked      2
Survived      0
dtype: int64

In [8]:
df = df.dropna()
df.isnull().sum()

Pclass      0
Sex         0
Age         0
Embarked    0
Survived    0
dtype: int64

In [9]:
df.sample(5)

Pclass     Sex   Age Embarked  Survived
25        3  female  38.0        S         1
200       3    male  28.0        S         0
758       3    male  34.0        S         0
687       3    male  19.0        S         0
382       3    male  32.0        S         0

In [10]:
df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [11]:
from sklearn.preprocessing import LabelEncoder
le_Sex = LabelEncoder()
le_Embarked = LabelEncoder()

In [12]:
df['Sex'] = le_Sex.fit_transform(df['Sex'])
df['Sex'].unique()

array([1, 0])

In [13]:
list(le_Sex.inverse_transform([1]))

['male']

In [14]:
df['Embarked'] = le_Embarked.fit_transform(df['Embarked'])
df['Embarked'].unique()

array([2, 0, 1])

In [15]:
df.head()

Pclass  Sex   Age  Embarked  Survived
0       3    1  22.0         2         0
1       1    0  38.0         0         1
2       3    0  26.0         2         1
3       1    0  35.0         2         1
4       3    1  35.0         2         0

In [16]:
X  = df[['Pclass','Sex','Age','Embarked']]
y = df[['Survived']]

In [17]:
from sklearn.tree import DecisionTreeClassifier
dec_tree_cla = DecisionTreeClassifier(random_state=0)
dec_tree_cla.fit(X, y.values)

DecisionTreeClassifier(random_state=0)

In [18]:
y_pred = dec_tree_cla.predict(X)
y_pred

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,

In [19]:
X = np.array([[2,'female',24,'S']])
X

array([['2', 'female', '24', 'S']], dtype='<U21')

In [20]:
X[:,1] = le_Sex.transform(X[:,1])
X[:,3] = le_Embarked.transform(X[:,3])
X

array([['2', '0', '24', '2']], dtype='<U21')

In [21]:
dec_tree_cla.predict(X)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])

In [22]:
data = {'model':dec_tree_cla,'le_Sex':le_Sex,'le_Embarked':le_Embarked}
with open('deployment.pkl','wb') as file:
  pickle.dump(data,file)

In [23]:
!pip install streamlit

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 44.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 90.0 MB/s eta 0:00:00


In [24]:
%%writefile app.py
import streamlit as st
import pickle
import numpy as np



def load_model():
  with open('deployment.pkl','rb') as file:
    data = pickle.load(file)
  return data

data = load_model()

model = data['model']
le_Sex = data['le_Sex']
le_Embarked = data['le_Embarked']

st.title("Titanic Survival")

Sex = ('male', 'female')
Embarked = ('S', 'C', 'Q')
Pclass = (1, 2, 3)

Pclass = st.selectbox('Pclass', Pclass)
Sex = st.selectbox('Sex', Sex)
Age = st.number_input('Age')
Embarked = st.selectbox('Embarked', Embarked)

ok = st.button("Survival Probality")
if ok:
   X = np.array([[Pclass,Sex,Age,Embarked]])
   X[:,1] = le_Sex.transform(X[:,1])
   X[:,3] = le_Embarked.transform(X[:,3])
   Survival = model.predict(X)
   if Survival == 1:
     st.write(" You will Survive.")
   else:
     st.write("You will not Survive.")



Writing app.py


In [25]:
!streamlit run app.py & npx localtunnel --port 8501

⠙⠹⠸⠼⠴⠦⠧⠇⠏

⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇Need to install the following packages:
localtunnel@2.0.2
Ok to proceed? (y) 
  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://35.229.194.163:8501

y

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸your url is: https://slick-crews-draw.loca.lt
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
  Stopping...
^C
